### ISSUE TITLE
Add responsive design in Home page.

### ISSUE THREAD

**Issue by FrenrihrCode** [FrenrihrCode/blog-netlify-cms#8]
Añadir diseño responsivo a la página principal del blog. @NOTCompile

**Comment by NOTCompile** [comment]
Responsive design in Home page.

FINISHED PE
Nota*: Acepta pe causita, no haga roche

**Comment by FrenrihrCode** [comment]
Te falta subir el PR, además de arreglar las etiquetas <text> el cual no existe, se recomienda usar <span> o similares.

**Comment by NOTCompile** [comment]
Ahora si acepta pe causita :'u
